name: Build Artifacts

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.txt
        base64 --decode keystore.txt > bekeystore.jks
    - name: Create artifacts
      env:
        keystore_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias: frog
      run: |
        git clone --depth=1 --branch=erekir https://github.com/Anuken/Mindustry
        cd Mindustry
        sed -i 's/applicationId "io.anuke.mindustry"/applicationId "io.anuke.mindustry.be"/g' android/build.gradle
        sed -i 's/"io.anuke.mindustry"/"io.anuke.mindustry.be"/g' android/AndroidManifest.xml
        sed -i 's/Mindustry/Mindustry BE/g' android/res/values/strings.xml
        ./gradlew pack
        ./gradlew desktop:dist server:dist android:assembleDebug --stacktrace
    - name: find
      run: |
        find
        find > find.file
    - name: Upload find
      uses: actions/upload-artifact@v3
      with:
        name: find
        path: ./find.file
    - name: Upload built jar file（desktop）
      uses: actions/upload-artifact@v3
      with:
        name: desktop
        path: ./Mindustry/desktop/build/libs/Mindustry.jar
    - name: Upload built jar file (server)
      uses: actions/upload-artifact@v3
      with:
        name: server
        path: ./Mindustry/server/build/libs/server-release.jar
    - name: Upload built apk file
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: ./Mindustry/android/build/outputs/apk/debug/android-debug.apk
