name: Build Artifacts

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Create artifacts
      run: |
        git clone --depth=1 --branch=master https://github.com/Anuken/Mindustry
        cd Mindustry
        sed -i 's/applicationId "io.anuke.mindustry"/applicationId "io.anuke.mindustry.v7"/g' android/build.gradle
        sed -i 's/"io.anuke.mindustry"/"io.anuke.mindustry.v7"/g' android/AndroidManifest.xml
        sed -i 's/Mindustry/Mindustry V7/g' android/res/values/strings.xml
        ./gradlew pack
        ./gradlew desktop:dist server:dist android:assembleDebug -Pbuildversion=136 -PversionType=alpha --stacktrace
    - name: Upload built jar file（desktop）
      uses: actions/upload-artifact@v3
      with:
        name: desktop
        path: ./Mindustry/desktop/build/libs/Mindustry.jar
    - name: Upload built jar file (server)
      uses: actions/upload-artifact@v3
      with:
        name: server
        path: ./Mindustry/server/build/libs/server-release.jar
    - name: Upload built apk file
      uses: actions/upload-artifact@v3
      with:
        name: android
        path: ./Mindustry/android/build/outputs/apk/debug/android-debug.apk
    - name: Upload artifacts (desktop)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Mindustry/desktop/build/libs/Mindustry.jar
        tag: Erekir
    - name: Upload artifacts (server)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Mindustry/server/build/libs/server-release.jar{{ env.RELEASE_VERSION }}.jar
        tag: Erekir
    - name: Upload artifacts (android)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Mindustry/android/build/outputs/apk/debug/android-debug.apk{{ env.RELEASE_VERSION }}.jar
        tag: Erekir
